# Generated by Django 5.2.8 on 2025-12-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client_admin', 'Client Admin'), ('manager', 'Manager'), ('employee', 'Employee'), ('team_lead', 'Team Lead')], default='employee', max_length=20),
        ),
    ]
