# Generated by Django 5.2.9 on 2025-12-25 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('tasks', '0003_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
    ]
