# Generated by Django 5.2.8 on 2025-12-19 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
