# Generated by Django 6.0 on 2025-12-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_alter_timesheet_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
